// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAcademicTrainingFields {
  /** name */
  name?: string | undefined;

  /** title */
  title?: string | undefined;

  /** type */
  type?: "bachelor" | "university" | "course" | undefined;

  /** Date start */
  dateStart?: string | undefined;

  /** Date End */
  dateEnd?: string | undefined;

  /** institute */
  institute?: string | undefined;

  /** description */
  description?: string | undefined;
}

export interface IAcademicTraining extends Entry<IAcademicTrainingFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "academicTraining";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IAuthorFields {
  /** name */
  name?: string | undefined;

  /** resume */
  resume?: string | undefined;

  /** socialMedia */
  socialMedia?: Record<string, any> | undefined;

  /** Profile Pic */
  profilePic?: Asset | undefined;

  /** bio */
  bio?: string | undefined;

  /** services */
  services?: IService[] | undefined;

  /** Jobs */
  jobs?: IJob[] | undefined;

  /** email */
  email?: string | undefined;

  /** phone */
  phone?: string | undefined;

  /** education */
  education?: IAcademicTraining[] | undefined;
}

export interface IAuthor extends Entry<IAuthorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "author";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBlogPostFields {
  /** title */
  title: string;

  /** slug */
  slug?: string | undefined;

  /** Publish Date */
  publishDate?: string | undefined;

  /** resume */
  resume?: string | undefined;

  /** Body */
  body?: Document | undefined;

  /** tags */
  tags?: Entry<{ [fieldId: string]: unknown }>[] | undefined;

  /** Featured Image */
  featuredImage?: Asset | undefined;
}

/** Blog post entry */

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogPost";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IJobFields {
  /** Name */
  name?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** Date start */
  start?: string | undefined;

  /** Date end */
  end?: string | undefined;

  /** description */
  description?: string | undefined;

  /** skills */
  skills?: ISkill[] | undefined;

  /** projects */
  projects?: IProject[] | undefined;

  /** Current job */
  currentJob?: boolean | undefined;
}

export interface IJob extends Entry<IJobFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "job";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IProjectFields {
  /** title */
  title?: string | undefined;

  /** description */
  description?: Document | undefined;

  /** date */
  date?: string | undefined;

  /** preview */
  preview?: Asset | undefined;

  /** url */
  url?: string | undefined;

  /** outcome */
  outcome?: Document | undefined;

  /** Skills */
  skills?: ISkill[] | undefined;
}

/** projects in which he contributed */

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "project";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IServiceFields {
  /** Title */
  title?: string | undefined;

  /** Description */
  description?: Document | undefined;

  /** featuredImage */
  featuredImage?: Asset | undefined;

  /** active */
  active?: boolean | undefined;

  /** Examples */
  examples?: Entry<{ [fieldId: string]: unknown }>[] | undefined;
}

/** descripción de los servicios que ofresco */

export interface IService extends Entry<IServiceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "service";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ISkillFields {
  /** name */
  name?: string | undefined;

  /** description */
  description?: string | undefined;

  /** image */
  image?: Asset | undefined;

  /** Type */
  type?: "lang" | "frontend" | "backend" | "db" | undefined;

  /** Years */
  years?: number | undefined;
}

/** skills descriptions */

export interface ISkill extends Entry<ISkillFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "skill";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITagFields {
  /** Tag */
  tag: string;
}

/** Blog post tag */

export interface ITag extends Entry<ITagFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tag";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "academicTraining"
  | "author"
  | "blogPost"
  | "job"
  | "project"
  | "service"
  | "skill"
  | "tag";

export type LOCALE_CODE = "en-US" | "es-MX";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "es-MX";
